# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Majeedr
email: majeedreporters@gmail.com
description: >
  Majeedr is awesome.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beta.majeedr.com/" # the base hostname & protocol for your site
twitter_username: majeedrofficial
github_username:  majeedr

permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown

# paginate
gems: [jekyll-paginate]
paginate: 12
paginate_path: "/page:num/"

#vars
picture_url_big: http://loremflickr.com/g/500/500/panorama
picture_url_small: http://loremflickr.com/g/50/100/panorama

# exclude
exclude:
  - package.json
  - gruntfile.js
  - node_modules
